<?php

namespace app\controllers\api;

use app\models\User;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\rest\Controller;
use \app\models\Person;
use yii\web\Response;
use yii\rest\ActiveController;

class PersonController extends ActiveController
{
    public $modelClass = 'app\models\Person';

//    public function init()
//    {
//        parent::init(); // TODO: Change the autogenerated stub
//        \Yii::$app->user->enableSession = false;
//    }

    public function behaviors()
    {

        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['access'] = [
            'class' => \yii\filters\AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'actions' => ['index', 'view'],
//                    'roles' => ['admin', 'employee']
                ],
                [
                    'allow' => false
                ]
            ]
        ];

        $behaviors['contentNegotiator'] = [

            'class' => 'yii\filters\ContentNegotiator',
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ]

        ];
        $behaviors['verbs'] = [
            'class' => VerbFilter::className(),
            'actions' => [
                'index' => ['GET'],
                'view' => ['GET'],
            ],
        ];
//        unset($behaviors['authenticator']);
//        $behaviors['authenticator'] = [
//            'class' => \yii\filters\auth\CompositeAuth::className(),
//            'authMethods' => [
//                \yii\filters\auth\HttpBasicAuth::className(),
//                \yii\filters\auth\HttpBearerAuth::className(),
//                \yii\filters\auth\QueryParamAuth::className(),
//            ],
//        ];
        return $behaviors;
    }


}